package com.umg.type;

public enum TipoToken {
    SIMBOLO_PALABRA_RESERVADA,
    SIMBOLO_AGRUPACION,
    SIMBOLO_RELACIONAL,
    SIMBOLO_SEPARADOR,
    SIMBOLO_INCREMENTO,
    SIMBOLO_ASIGNACION,
    SIMBOLO_NUMERICO,
    SIMBOLO_IDENTIFICADOR,
    SIMBOLO_INVALIDO
}
